# Generated by Django 4.1.1 on 2022-11-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_book_image_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
