# Generated by Django 4.1.1 on 2022-11-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_remove_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time',
            new_name='timestamp',
        ),
    ]
