# Generated by Django 4.1.1 on 2022-11-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_rename_time_record_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
